https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

## Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[7.9541e+37, 4.5745e-41, 7.9541e+37],
        [4.5745e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.4065e+34, 4.5745e-41, 1.1351e-43]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2434, 0.3485, 0.6931],
        [0.4568, 0.6452, 0.6402],
        [0.8457, 0.4212, 0.5105],
        [0.6025, 0.6957, 0.2970],
        [0.2428, 0.8630, 0.6448]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.4103, -0.2845, -0.7349],
        [ 0.8428,  1.5913, -0.5741],
        [-0.9948, -0.9658, -0.0822],
        [ 1.6971, -0.0885,  0.5296],
        [-0.1100,  0.4583, -0.1400]])


In [7]:
print(x.size())

torch.Size([5, 3])


## Operations

In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.1536,  0.0564, -0.4536],
        [ 0.9563,  2.3915,  0.1946],
        [-0.0142, -0.1663,  0.9088],
        [ 2.4659,  0.6206,  1.4499],
        [ 0.5229,  0.7037,  0.5871]])


In [9]:
print(torch.add(x, y))

tensor([[ 1.1536,  0.0564, -0.4536],
        [ 0.9563,  2.3915,  0.1946],
        [-0.0142, -0.1663,  0.9088],
        [ 2.4659,  0.6206,  1.4499],
        [ 0.5229,  0.7037,  0.5871]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.1536,  0.0564, -0.4536],
        [ 0.9563,  2.3915,  0.1946],
        [-0.0142, -0.1663,  0.9088],
        [ 2.4659,  0.6206,  1.4499],
        [ 0.5229,  0.7037,  0.5871]])


Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.1536,  0.0564, -0.4536],
        [ 0.9563,  2.3915,  0.1946],
        [-0.0142, -0.1663,  0.9088],
        [ 2.4659,  0.6206,  1.4499],
        [ 0.5229,  0.7037,  0.5871]])


In [12]:
print(x[:, 1])

tensor([-0.2845,  1.5913, -0.9658, -0.0885,  0.4583])


Resizing: If you want to resize/reshape tensor, you can use `torch.view`:

In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, `use .item()` to get the value as a Python number

In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.5789])
0.5788513422012329


## NUMPY BRIDGE

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will **share their underlying memory locations, and changing one will change the other**.

In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA TENSORS

In [19]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda:0")            # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                                        # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([1.5789], device='cuda:0')
tensor([1.5789], dtype=torch.float64)
